:concurrency: 5
development:
  :concurrency: 3
production:
  :concurrency: 1
:queues:
  - default
:schedule:
  certificate_verification:
    every: 20m
    class: CertificateVerificationJob
    queue: default
